# https://hub.docker.com/r/bentopdf/bentopdf

services:
  bentopdf:
    container_name: bentopdf
    image: ghcr.io/alam00000/bentopdf-simple:v2.0.0
    extends:
      file: ../base.yml
      service: base
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      # override hostname to just 'pdf'
      - "traefik.http.routers.bentopdf.rule=HostRegexp(`^pdf\\..+`)"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$$"

include:
  - ../network.yml
